development:
  token_discovery:
    class: TokenDiscoveryJob
    queue: token_discovery
    schedule: every 30 seconds

  whale_monitor:
    class: WhaleMonitorJob
    queue: default
    schedule: every 30 seconds

  price_updates:
    class: TokenPriceUpdateJob
    queue: token_scan
    schedule: every 60 seconds

  daily_scan_reset:
    class: DailyScanResetJob
    queue: default
    schedule: at midnight every day

production:
  token_discovery:
    class: TokenDiscoveryJob
    queue: token_discovery
    schedule: every 10 seconds

  whale_monitor:
    class: WhaleMonitorJob
    queue: default
    schedule: every 15 seconds

  price_updates:
    class: TokenPriceUpdateJob
    queue: token_scan
    schedule: every 60 seconds

  daily_scan_reset:
    class: DailyScanResetJob
    queue: default
    schedule: at midnight every day
